### ISSUE TITLE
Do you have any plans about providing the checkpoint of the model ? 

### ISSUE THREAD

**Issue by thanit456** [vistec-AI/Thai-NNER#1]
If you will provide, Please tell me when

**Comment by WeerayutBu** [comment]
Sorry for the late reply; I just added a link for Colab and checkpoints in the README. 

You can download the data and checkpoints from the link below:
https://drive.google.com/drive/folders/1hQ3HYI3sBJqpeabUMSVGGMdTHalCEv-5?usp=sharing

And how to use the model on Colab: 
https://colab.research.google.com/drive/16m7Vx0ezLpPY2PQLlIMlbfmI9KBO5o7A?usp=sharing

**Comment by thanit456** [comment]
Thanks for providing checkpoints
