### ISSUE TITLE
Preprints

### ISSUE THREAD

**Issue by Bancherd-DeLong** [vistec-AI/Thai-NNER#2]
ถัามี รบกวลขอ preprint ได้มั้ยครับ?

ขอบคุณครับ

บรรเจิด

bancherddelong(at)gmail(dot)com

**Comment by Bancherd-DeLong** [comment]
และผมได้ลอง colab แล้วเกิด error ตาม นี้ ครับ ผมไม่ค่อยรู้เรื่อง ลองค้นในweb แต่ก็ยังแก้ไม่ได้ครับ
![thai-nner_colab](https://user-images.githubusercontent.com/30105665/162694432-f0fc71db-c716-4ac0-a35a-dd9bb8bba7c4.png)

**Comment by mrpeerat** [comment]
Hi, thank you for the comment. 

For the preprint, link: https://github.com/vistec-AI/Thai-NNER/files/8497522/thai_nested_named_entity_recognition_corpus.pdf
For the error, please wait for @WeerayutBu to answer this question.

Best,
Peerat

**Comment by Bancherd-DeLong** [comment]
Tx.  :~)

**Comment by WeerayutBu** [comment]
Thanks for the issues and sorry for the late reply.

The broken link caused the problem; I fixed it.

To run test_nne.py,  you have to download the data [lm, checkpoints, dataset] directly from the link provided in the Github, then save it in the directory [data/.]. After finishing the previous step, you can skip the download part in the Colab.

Best,
Weerayut

**Comment by c4n** [comment]
The issue seems to be resolved.
