### ISSUE TITLE
Where is the annotation guideline ?

### ISSUE THREAD

**Issue by thangld201** [vistec-AI/Thai-NNER#7]
Hi, @wannaphong @WeerayutBu @c4n @mrpeerat, thank you very much for the works!

I need information on each entity tag type (esp. fine-grained tags) for some manual evaluation. Could you share the guideline ?

**Comment by mrpeerat** [comment]
I will let @WeerayutBu answer this one. We have the guideline, but I think we might forget to put it online.

**Comment by WeerayutBu** [comment]
Sorry for the late reply!  I've uploaded the guideline to the dataset directory here: https://drive.google.com/drive/u/1/folders/1Dy-360iZ9hIA-xA0yizSwmpM8sx6rrjJ
Thank you for pointing it out.
